#!/bin/ruby

if (ARGV.length == 1 && ARGV[0] == "-h")
    puts("USAGE")
    puts("  ./201yams d1 d2 d3 d4 d5 c")
    puts("")
    puts("DESCRIPTION")
    puts("  d1  value of the first die (0 if not thrown)")
    puts("  d2  value of the second die (0 if not thrown)")
    puts("  d3  value of the third die (0 if not thrown)")
    puts("  d4  value of the fourth die (0 if not thrown)")
    puts("  d5  value of the fifth die (0 if not thrown)")
    puts("  c   expected combination")
end
